name: Deploy to Local Server via SSH and Rsync

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.GITRSYNCH_VCSAJMPHOST }}

    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p 4422 203.59.236.101 >> ~/.ssh/known_hosts

    - name: Rsync files to the server
      run: rsync -avz -e "ssh -p 4422" --delete --exclude='.github/'  ./ snetop@203.59.236.101:/var/www/html/website01/


