name: Deploy to Local Server via SSH and Rsync

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.GITRSYNCH_VCSAJMPHOST }}

    - name: Rsync files to the server
      run: rsync -avz -e "ssh -p 4422" --delete ./ snetop@203.59.236.101:/var/www/html/
